variables:
  UPSTREAM_GIT_URL: 'https://github.com/jpillora/chisel.git'
  UPSTREAM_DOCKERFILE_PATH: '.'

stages:
  - docker-get-version
  - docker-build
  - docker-push

include:
  - project: applications/tooling
    ref: main
    file: 'gitlab-ci-includes/build-oci-image.yml'

docker-chisel-image-get-version:
  stage: docker-get-version
  extends: .docker:get-version
  image: bash:latest
  variables:
    UPSTREAM_GIT_URL: 'https://github.com/jpillora/chisel.git'
    UPSTREAM_DOCKERFILE_PATH: '.'
    IMAGE_NAME: 'chisel'
  script:
    - |
      OPWD=$(pwd)
      IMAGE_NAME="${IMAGE_NAME:-$(basename "${CI_REGISTRY_IMAGE}")}"

      apk add git || apt install git
      git clone ${UPSTREAM_GIT_URL} "${OPWD}/build-tmp"
      cd "${OPWD}/build-tmp"
      latest_tag=$(git describe --abbrev=0 --tags)
      cd "${OPWD}"
      echo "VERSION_TAGS[latest]=${latest_tag}" | tee -a ${IMAGE_NAME}-VERSION_TAGS
      cat ${IMAGE_NAME}-VERSION_TAGS
      readlink -f "${IMAGE_NAME}-VERSION_TAGS"

docker-chisel-image-build:
  stage: docker-build
  extends: .docker:build-image-from-upstream
  variables:
    UPSTREAM_GIT_URL: 'https://github.com/jpillora/chisel.git'
    UPSTREAM_DOCKERFILE_PATH: '.'
    IMAGE_NAME: 'chisel'

docker-chisel-image-push:
  stage: docker-push
  extends: .docker:push-image-to-registry
  variables:
    UPSTREAM_GIT_URL: 'https://github.com/jpillora/chisel.git'
    UPSTREAM_DOCKERFILE_PATH: '.'
    IMAGE_NAME: 'chisel'

docker-syncoid-server-image-get-version:
  stage: docker-get-version
  extends: .docker:get-version
  image: bash:latest
  variables:
    DOCKERFILE_PATH: 'pull-server'
    DOCKERFILE_NAME: 'Dockerfile.syncoid-pull-server'
    IMAGE_NAME: 'syncoid-pull-server'
    #TODO: Tags/versions should track the upstream gitlab-runner image
  script:
    - |
      IMAGE_NAME="${IMAGE_NAME:-$(basename "${CI_REGISTRY_IMAGE}")}"
      echo "VERSION_TAGS[latest]=jammy" | tee -a ${IMAGE_NAME}-VERSION_TAGS

docker-syncoid-server-image-build:
  stage: docker-build
  extends: .docker:build-image-from-dockerfile
  variables:
    DOCKERFILE_PATH: 'pull-server'
    DOCKERFILE_NAME: 'Dockerfile.syncoid-pull-server'
    IMAGE_NAME: 'syncoid-pull-server'

docker-syncoid-server-image-push:
  stage: docker-push
  extends: .docker:push-image-to-registry
  variables:
    DOCKERFILE_PATH: 'pull-server'
    DOCKERFILE_NAME: 'Dockerfile.syncoid-pull-server'
    IMAGE_NAME: 'syncoid-pull-server'

docker-sanoid-client-image-get-version:
  stage: docker-get-version
  extends: .docker:get-version
  image: bash:latest
  variables:
    DOCKERFILE_PATH: 'pull-client'
    DOCKERFILE_NAME: 'Dockerfile.syncoid-pull-client'
    IMAGE_NAME: 'syncoid-pull-client'
  script:
    - |
      IMAGE_NAME="${IMAGE_NAME:-$(basename "${CI_REGISTRY_IMAGE}")}"
      echo "VERSION_TAGS[latest]=jammy" | tee -a ${IMAGE_NAME}-VERSION_TAGS

docker-sanoid-client-image-build:
  stage: docker-build
  extends: .docker:build-image-from-dockerfile
  variables:
    DOCKERFILE_PATH: 'pull-client'
    DOCKERFILE_NAME: 'Dockerfile.syncoid-pull-client'
    IMAGE_NAME: 'syncoid-pull-client'

docker-sanoid-client-image-push:
  stage: docker-push
  extends: .docker:push-image-to-registry
  variables:
    DOCKERFILE_PATH: 'pull-client'
    DOCKERFILE_NAME: 'Dockerfile.syncoid-pull-client'
    IMAGE_NAME: 'syncoid-pull-client'

.run-backups:
  tags:
    TODO
  image: cr.ghanima.net/applications/sanoid-helper-scripts/syncoid-pull:latest
  script: |
    echo "Hi"
    exit 0
