version: '3.8'
services:
  nginx-ingress:
    image: 'nginx'
    restart: always
    container_name: 'nginx-ingress'
    hostname: 'nginx-ingress'
    environment:
  chisel:
    image: 'gitlab/gitlab-ce:15.9.2-ce.0'
    restart: always
    container_name: 'nginx-ingress'
    hostname: 'nginx-ingress'
  gitlabrunner:
    image: gitlab/gitlab-runner:v15.16.0
    restart: always
    container_name: runner
    hostname: runner
    environment:
      TZ: Europe/Luxembourg
    volumes:
      - 'gitlab_runner_config:/etc/gitlab-runner'
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

