version: '3.8'
configs:
  gitlabrunner_config:
    file: ${DEPLOYMENT}/config.toml
  chisel_users:
    file: ${DEPLOYMENT}/users.json
  nginx_conf:
    file: ${DEPLOYMENT}/nginx.conf
  nginx_http_conf:
    file: ${DEPLOYMENT}/http.conf
  nginx_https_conf:
    file: ${DEPLOYMENT}/https.conf
services:
  nginx-ingress:
    image: 'nginx:latest'
    restart: always
    command: |
      /bin/sh -c '
        while :; do
          sleep 5m & wait $${!};
          ls /etc/letsencrypt/live/${PUBLIC_FQDN}/fullchain.pem
          if [-e /etc/letsencrypt/live/${PUBLIC_FQDN}/fullchain.pem ]; then
            echo "Enabling SSL"
            cp /tmp/https.conf /etc/nginx/conf.d/http.conf;
          else
            echo "Not enabling SSL"
          fi;
          nginx -s reload;
        done &
        nginx -g \"daemon off;\"'"
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
        uid: "0"
        gid: "0"
        mode: 0644
      - source: nginx_http_conf
        target: /etc/nginx/conf.d/http.conf
        uid: "0"
        gid: "0"
        mode: 0644
      - source: nginx_https_conf
        target: /tmp/https.conf
        uid: "0"
        gid: "0"
        mode: 0644
    hostname: 'nginx-ingress'
    environment:
      TZ: Europe/Luxembourg
      PUBLIC_FQDN: $PUBLIC_FQDN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
  certbot:
    image: certbot/certbot
    entrypoint: |
      /bin/sh -c '
        trap exit TERM;
        if [ ! -e /etc/letsencrypt/live/${PUBLIC_FQDN}/fullchain.pem ]; then
          certbot \
            certonly \
            --webroot -w /var/www/certbot \
            --email ${CERTBOT_EMAIL} \
            -d ${PUBLIC_FQDN} \
            --rsa-key-size 4096 \
            --agree-tos \
            --force-renewal
        fi
        while :; do certbot renew; sleep 12h & wait $${!}; done;
      '
    environment:
      TZ: Europe/Luxembourg
      PUBLIC_FQDN: $PUBLIC_FQDN
      CERTBOT_EMAIL: $CERTBOT_EMAIL
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
  chisel:
    image: 'cr.ghanima.net/applications/sanoid/chisel:latest'
    command: [ "server", "-v", "--host", "0.0.0.0", "--port", "8081", "--keepalive", "45s", "--authfile", "/etc/chisel/users.json"]
    configs:
      - source: chisel_users
        target: /etc/chisel/users.json
        uid: "0"
        gid: "0"
        mode: 0444
    restart: always
    environment:
      TZ: Europe/Luxembourg
  gitlabrunner:
    image: gitlab/gitlab-runner:v16.0.0
    configs:
      - source: gitlabrunner_config
        target: /etc/gitlab-runner/config.toml
        uid: "0"
        gid: "0"
        mode: 0600
    restart: always
    hostname: runner
    environment:
      TZ: Europe/Luxembourg
    volumes:
      - 'gitlab_runner_config:/etc/gitlab-runner'
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  gitlab_runner_config:
  certbot_conf:
  certbot_www: