FROM ubuntu:jammy
RUN apt install -y zfsutils-linux openssh-server mbuffer lzop
RUN mkdir -p /var/lib/syncoid




## Outside
# sudo zfs create SLAB/Backups/Syncoid/ph3.local
# sudo zfs allow -u 600 receive,aclinherit,hold,userprop SLAB/Backups/Syncoid/ph3.local