concurrent = 5
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "lu.ghanima.local (docker)"
  url = "https://git.ghanima.net/"
  token = ""
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    pull_policy = "if-not-present"
    allowed_pull_policies = ["always", "if-not-present", "never"]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/certs/client", "/cache"]
    shm_size = 0